upstream fastcgi_backend {
    server php:9000;
}
server {
    listen 80;
    server_name localhost;
    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;
    include /var/www/html/nginx.conf.sample;
    fastcgi_param MAGE_RUN_TYPE website;
    fastcgi_param MAGE_RUN_CODE wands;
}
