#!/usr/bin/env python3
"""Reuse immutable generated bytes after a review-policy change; never transfer acceptance."""
import argparse
from contextlib import ExitStack
import json
from pathlib import Path
import shutil
import time

from bulk_expansion_images import atomic_json, connect, descriptor, lock, status
from build_expanded_catalog import canonical, digest
from prepare_catalog import sha256


def migrate(source, target):
    source=source.resolve();target=target.resolve()
    old=json.loads((source/'run.json').read_text());new=descriptor(target)
    if {k:v for k,v in old.items() if k!='review_identity'}!={k:v for k,v in new.items() if k!='review_identity'}:
        raise ValueError('Generation inputs differ; migration refused')
    if (target/'migration.json').exists():raise ValueError('Migration already recorded')
    with ExitStack() as stack:
        for run in (source,target):
            for name in ('supervisor','generation','review','reference-review','reference-repair-review'):
                stack.enter_context(lock(run,name))
        src=connect(source);dst=connect(target)
        if dst.execute("SELECT count(*) FROM jobs WHERE state!='pending'").fetchone()[0] or dst.execute('SELECT count(*) FROM reference_repairs').fetchone()[0]:
            raise ValueError('Target must be unused')
        def copy(path, expected):
            path=Path(path);relative=path.relative_to(source)
            if sha256(path)!=expected:raise ValueError('Source image changed')
            dest=target/relative;dest.parent.mkdir(parents=True,exist_ok=True)
            if dest.exists() and sha256(dest)!=expected:raise ValueError('Destination collision')
            if not dest.exists():shutil.copy2(path,dest)
            return str(dest)
        transferred=0;repairs=0
        with dst:
            for row in src.execute('SELECT * FROM jobs WHERE image_path IS NOT NULL'):
                fresh=dst.execute('SELECT request FROM jobs WHERE job_id=?',(row['job_id'],)).fetchone()
                if fresh is None or fresh['request']!=row['request']:raise ValueError('Job changed')
                for path in Path(row['image_path']).parent.iterdir():
                    if path.is_file():copy(path,sha256(path))
                path=copy(row['image_path'],row['image_sha256'])
                dst.execute("UPDATE jobs SET state='generated',attempts=?,image_path=?,image_sha256=?,review=NULL,error=NULL,updated=? WHERE job_id=?",
                            (row['attempts'],path,row['image_sha256'],time.time(),row['job_id']))
                transferred+=1
            for row in src.execute('SELECT r.*,s.design FROM reference_repairs r JOIN references_to_review s ON s.image_sha256=r.original_sha256 AND s.design_sha256=r.design_sha256'):
                matches=[]
                for ref in dst.execute('SELECT * FROM references_to_review WHERE image_sha256=?',(row['original_sha256'],)):
                    design=json.loads(ref['design']);design.pop('product_class',None)
                    old_design=json.loads(row['design']);old_design.pop('product_class',None)
                    if design==old_design:matches.append(ref)
                if len(matches)!=1:raise ValueError('Reference mapping ambiguous or missing')
                path=copy(row['image_path'],row['image_sha256'])
                metadata=Path(row['image_path']).with_suffix('.json')
                if metadata.exists():copy(metadata,sha256(metadata))
                dst.execute('INSERT INTO reference_repairs VALUES(?,?,?,?,?,NULL)',
                            (row['original_sha256'],matches[0]['design_sha256'],row['attempt'],path,row['image_sha256']))
                repairs+=1
        src.close();dst.close()
        atomic_json(target/'migration.json',{'source':str(source),'source_descriptor_sha256':sha256(source/'run.json'),
            'target_descriptor_sha256':sha256(target/'run.json'),'images':transferred,'repairs':repairs,
            'acceptances_transferred':0,'reason':'Corrected product-class and requested-color review context',
            'prior_review_history':str(source/'ledger.sqlite'),'created':time.time()})
    return status(target)

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source',type=Path,required=True);p.add_argument('--target',type=Path,required=True)
    a=p.parse_args();print(json.dumps(migrate(a.source,a.target),indent=2))
